openapi: 3.0.0
info:
  description: Serviços REST relacionados a empresas externas.
  version: 1.0.0
  title: Documentação API Public
  contact:
    name: Contmatic Phoenix
    url: https://contmatic.com.br
    email: comercial@contmatic.com.br
tags:
  - name: Empresa
    description: Serviços relacionados as empresas dos clientes
  - name: Metadata
    description: Serviços relacionados com as informações dos arquivos
  - name: File
    description: Serviços relacionados com o arquivo
paths:
  /v1/empresas:
    get:
      tags:
        - Empresa
      summary: Serviço destinado à consulta de empresas
      operationId: getEmpresasUsingGET
      parameters:
        - name: alteradoApos
          in: query
          required: false
          schema:
            type: string
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: size
          in: query
          required: false
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EmpresaResource"
        "400":
          description: Solicitação Inválida
        "401":
          description: Não Autorizado
        "403":
          description: Proibido
        "404":
          description: Não Encontrado
        "422":
          description: Solicitação não executada pois o request não cumpre as constraints
      security:
        - password_jwt: []
  "/v1/files/{codigo}":
    get:
      tags:
        - File
      summary: Serviço destinado à donwload de arquivos.
      operationId: getFileUsingGET
      parameters:
        - name: codigo
          in: path
          description: Codigo metadata do arquivo a ser baixado.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ByteArrayResource"
            application/octet-stream:
              schema:
                $ref: "#/components/schemas/ByteArrayResource"
        "400":
          description: Solicitação Inválida
        "401":
          description: Não Autorizado
        "403":
          description: Proibido
        "404":
          description: Não Encontrado
        "422":
          description: Solicitação não executada pois o request não cumpre as constraints
      security:
        - password_jwt: []
  /v1/metadatas:
    get:
      tags:
        - Metadata
      summary: Serviço destinado à consulta de metadatas
      operationId: getMetadatasUsingGET
      parameters:
        - name: alteradoApos
          in: query
          required: false
          schema:
            type: string
        - name: empresa
          in: query
          required: false
          schema:
            type: string
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: size
          in: query
          required: false
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MetadataResource"
        "400":
          description: Solicitação Inválida
        "401":
          description: Não Autorizado
        "403":
          description: Proibido
        "404":
          description: Não Encontrado
        "422":
          description: Solicitação não executada pois o request não cumpre as constraints
      security:
        - password_jwt: []
servers:
  - url: //api.contmatic.com.br:443/public
components:
  securitySchemes:
    password_jwt:
      type: apiKey
      name: Authorization
      in: header
  schemas:
    ByteArrayResource:
      type: object
      properties:
        byteArray:
          type: string
          format: byte
        description:
          type: string
        file:
          type: object
        filename:
          type: string
        inputStream:
          $ref: "#/components/schemas/InputStream"
        open:
          type: boolean
        readable:
          type: boolean
        uri:
          type: string
          format: uri
        url:
          type: string
          format: url
      title: ByteArrayResource
    EmpresaResource:
      type: object
      properties:
        apelido:
          type: string
        caepf:
          type: string
        cei:
          type: string
        clienteId:
          type: integer
          format: int32
        cnpj:
          type: string
        cpf:
          type: string
        dataAlteracao:
          type: string
          format: date-time
        razaoSocial:
          type: string
      title: EmpresaResource
    InputStream:
      type: object
      title: InputStream
    MetadataResource:
      type: object
      properties:
        codigo:
          type: string
        dataAlteracao:
          type: string
          format: date-time
        empresa:
          type: string
        mode:
          type: string
        nome:
          type: string
        obrigacao:
          $ref: "#/components/schemas/ObrigacaoResource"
      title: MetadataResource
    ObrigacaoResource:
      type: object
      properties:
        dataVencimento:
          type: string
          format: date-time
        valor:
          type: number
      title: ObrigacaoResource
